[package]
name = "flanforge-store"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
flanforge-core = { workspace = true }
fs2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
