[package]
name = "flanforge-service-systemd"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
flanforge-core = { workspace = true }
flanforge-paths = { workspace = true }
flanforge-service = { workspace = true }
flanforge-service-files = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
flanforge-test-support = { workspace = true }
tempfile = "3"

[lints]
workspace = true
